"use server";

// Admin actions. Each one checks the admin again (actions are public endpoints), and the database's
// row-level security enforces the same rule underneath.
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { requireAdmin } from "@/lib/admin/guard";
import type { ImportRow } from "@/lib/admin/eventbrite";
import { sendWelcomeEmails, type WelcomeTarget } from "@/lib/email/welcome";
import { rows } from "@/lib/rows";
import { formatWhen, localToIso } from "@/lib/time";

const QUEST_TYPES = ["making", "tasting", "tradition", "performance", "social", "discovery", "puzzle", "multi_stop"];

function text(form: FormData, key: string, max = 200): string | null {
  const v = String(form.get(key) ?? "").trim().slice(0, max);
  return v === "" ? null : v;
}
function int(form: FormData, key: string): number | null {
  const v = text(form, key, 12);
  if (v === null) return null;
  const n = Number(v);
  return Number.isFinite(n) ? Math.round(n) : null;
}
function back(path: string, msg: string): never {
  redirect(`${path}${path.includes("?") ? "&" : "?"}msg=${encodeURIComponent(msg)}`);
}

// ---------------------------------------------------------------------------------------------
// Sessions
// ---------------------------------------------------------------------------------------------
function sessionFields(form: FormData) {
  const startsAt = localToIso(String(form.get("starts_at") ?? ""));
  let revealAt = localToIso(String(form.get("revealed_at") ?? ""));
  // No reveal time given: 48 hours before the start (docs/game-design.md, pre-game reveal).
  if (!revealAt && startsAt) revealAt = new Date(new Date(startsAt).getTime() - 48 * 3600 * 1000).toISOString();
  return {
    number: int(form, "number"),
    neighborhood: text(form, "neighborhood", 80),
    starts_at: startsAt,
    start_location: text(form, "start_location", 200),
    revealed_at: revealAt,
    is_finals: form.get("is_finals") === "on",
  };
}

export async function createSession(form: FormData) {
  const { supabase } = await requireAdmin();
  const seasonId = text(form, "season_id", 64);
  const fields = sessionFields(form);
  if (!seasonId || fields.number === null || fields.number < 1) back("/admin", "Pick a season and a session number.");
  const { data, error } = await supabase.from("session").insert({ season_id: seasonId, ...fields }).select("id").single();
  if (error || !data) back("/admin", error?.code === "23505" ? "That season already has a session with that number." : "Couldn't create the session.");
  revalidatePath("/admin");
  redirect(`/admin/sessions/${(data as { id: string }).id}?msg=${encodeURIComponent("Session created. Add its quests below.")}`);
}

export async function updateSession(form: FormData) {
  const { supabase } = await requireAdmin();
  const id = text(form, "id", 64);
  if (!id) back("/admin", "Missing session.");
  const fields = sessionFields(form);
  const { number: _n, ...rest } = fields;
  const { error } = await supabase.from("session").update(rest).eq("id", id);
  if (error) back(`/admin/sessions/${id}`, "Couldn't save the session.");
  revalidatePath(`/admin/sessions/${id}`);
  back(`/admin/sessions/${id}`, "Saved.");
}

// ---------------------------------------------------------------------------------------------
// Quests (codes are generated by the database)
// ---------------------------------------------------------------------------------------------
export async function createQuest(form: FormData) {
  const { supabase } = await requireAdmin();
  const sessionId = text(form, "session_id", 64);
  const title = text(form, "title", 120);
  const type = text(form, "type", 20);
  if (!sessionId || !title || !type || !QUEST_TYPES.includes(type)) back(`/admin/sessions/${sessionId}`, "A quest needs a title and a type.");
  const isHidden = form.get("is_hidden") === "on";
  const isJudged = form.get("is_judged") === "on";
  const xp = int(form, "xp") ?? (isHidden ? 30 : 25); // docs/game-design.md section 9
  const feeDollars = text(form, "host_fee", 12);
  const { error } = await supabase.from("quest").insert({
    session_id: sessionId,
    title,
    type,
    stop_number: isHidden || isJudged ? null : int(form, "stop_number"),
    xp: Math.max(1, xp),
    is_hidden: isHidden,
    is_judged: isJudged,
    host_id: text(form, "host_id", 64),
    max_points: int(form, "max_points"),
    host_fee_cents: feeDollars ? Math.round(Number(feeDollars) * 100) || null : null,
  });
  if (error) back(`/admin/sessions/${sessionId}`, "Couldn't add the quest.");
  revalidatePath(`/admin/sessions/${sessionId}`);
  back(`/admin/sessions/${sessionId}`, `Added "${title}".`);
}

export async function updateQuest(form: FormData) {
  const { supabase } = await requireAdmin();
  const id = text(form, "id", 64);
  const sessionId = text(form, "session_id", 64);
  const title = text(form, "title", 120);
  const type = text(form, "type", 20);
  if (!id || !title || !type || !QUEST_TYPES.includes(type)) back(`/admin/sessions/${sessionId}`, "A quest needs a title and a type.");
  const isHidden = form.get("is_hidden") === "on";
  const isJudged = form.get("is_judged") === "on";
  const feeDollars = text(form, "host_fee", 12);
  const { error } = await supabase
    .from("quest")
    .update({
      title,
      type,
      stop_number: isHidden || isJudged ? null : int(form, "stop_number"),
      xp: Math.max(1, int(form, "xp") ?? (isHidden ? 30 : 25)),
      is_hidden: isHidden,
      is_judged: isJudged,
      host_id: text(form, "host_id", 64),
      max_points: int(form, "max_points"),
      host_fee_cents: feeDollars ? Math.round(Number(feeDollars) * 100) || null : null,
    })
    .eq("id", id);
  revalidatePath(`/admin/sessions/${sessionId}`);
  // XP already earned for this quest stays as it was: progress only goes up.
  back(`/admin/sessions/${sessionId}`, error ? "Couldn't save the quest." : `Saved "${title}".`);
}

export async function deleteQuest(form: FormData) {
  const { supabase } = await requireAdmin();
  const id = text(form, "id", 64);
  const sessionId = text(form, "session_id", 64);
  const { error } = await supabase.from("quest").delete().eq("id", id);
  // Completed quests can't be deleted (a completion references them): progress only goes up.
  if (error) back(`/admin/sessions/${sessionId}`, "A team already completed that quest, so it stays.");
  revalidatePath(`/admin/sessions/${sessionId}`);
  back(`/admin/sessions/${sessionId}`, "Quest removed.");
}

// ---------------------------------------------------------------------------------------------
// Hosts
// ---------------------------------------------------------------------------------------------
export async function createHost(form: FormData) {
  const { supabase } = await requireAdmin();
  const business = text(form, "business", 120);
  const name = text(form, "name", 80);
  if (!business || !name) back("/admin/hosts", "A host needs a business and a contact name.");
  const { error } = await supabase.from("host").insert({ business, name, contact: text(form, "contact", 160) });
  if (error) back("/admin/hosts", "Couldn't add the host.");
  revalidatePath("/admin/hosts");
  back("/admin/hosts", `Added ${business}.`);
}

export async function deleteHost(form: FormData) {
  const { supabase } = await requireAdmin();
  const { error } = await supabase.from("host").delete().eq("id", text(form, "id", 64));
  if (error) back("/admin/hosts", "Couldn't remove that host.");
  revalidatePath("/admin/hosts");
  back("/admin/hosts", "Host removed.");
}

// ---------------------------------------------------------------------------------------------
// Player import (Eventbrite) and welcome emails
// ---------------------------------------------------------------------------------------------
export type ImportResult =
  | { ok: true; players_created: number; players_existing: number; tickets_added: number; tickets_existing: number; skipped: { row: number; email: string | null; reason: string }[] }
  | { ok: false; error: string };

export async function importPlayers(sessionId: string, importRows: ImportRow[]): Promise<ImportResult> {
  const { supabase } = await requireAdmin();
  if (!sessionId || !Array.isArray(importRows) || importRows.length === 0) return { ok: false, error: "Pick a session and a file first." };
  if (importRows.length > 2000) return { ok: false, error: "That's more than 2,000 rows. Split the file." };
  const clean = importRows.map((r) => ({
    email: String(r.email ?? "").slice(0, 254),
    name: String(r.name ?? "").slice(0, 120),
    coming_with: r.coming_with ? String(r.coming_with).slice(0, 60) : null,
    order_ref: r.order_ref ? String(r.order_ref).slice(0, 60) : null,
    ticket_type: r.ticket_type ? String(r.ticket_type).slice(0, 80) : null,
  }));
  const { data, error } = await supabase.rpc("import_players", { p_session_id: sessionId, p_rows: clean });
  if (error || !data) return { ok: false, error: error?.message ?? "The import failed." };
  revalidatePath("/admin");
  revalidatePath("/admin/players");
  return { ok: true, ...(data as Omit<Extract<ImportResult, { ok: true }>, "ok">) };
}

export type WelcomeResult = { sent: number; alreadyWelcomed: number; error: string | null };

export async function sendWelcome(sessionId: string): Promise<WelcomeResult> {
  const { supabase } = await requireAdmin();
  const [{ data: sessionRow }, { data: ticketRows }] = await Promise.all([
    supabase.from("session").select("number, neighborhood, starts_at, season:season_id (number, name)").eq("id", sessionId).single(),
    supabase.from("ticket").select("player:player_id (id, email, name, welcomed_at)").eq("session_id", sessionId),
  ]);
  const session = sessionRow as unknown as { number: number; neighborhood: string | null; starts_at: string | null; season: { number: number; name: string | null } | null } | null;
  if (!session) return { sent: 0, alreadyWelcomed: 0, error: "Session not found." };

  const players = rows<{ player: { id: string; email: string; name: string; welcomed_at: string | null } | null }>(ticketRows)
    .map((t) => t.player)
    .filter((p): p is NonNullable<typeof p> => !!p);
  const pending = players.filter((p) => !p.welcomed_at);
  if (pending.length === 0) return { sent: 0, alreadyWelcomed: players.length, error: null };

  const seasonName = session.season?.name ? `${session.season.name} ` : "";
  const ctx = {
    sessionLabel: `Colgrid ${seasonName}Session ${String(session.number).padStart(2, "0")}`,
    neighborhood: session.neighborhood,
    when: formatWhen(session.starts_at),
  };
  const targets: WelcomeTarget[] = pending.map((p) => ({ email: p.email, name: p.name }));
  const { sent, error } = await sendWelcomeEmails(targets, ctx);

  if (sent.length) {
    const sentIds = pending.filter((p) => sent.includes(p.email)).map((p) => p.id);
    await supabase.from("player").update({ welcomed_at: new Date().toISOString() }).in("id", sentIds);
  }
  revalidatePath("/admin/players");
  return { sent: sent.length, alreadyWelcomed: players.length - pending.length, error };
}

// Remove a ticket (e.g. a refund). Only before they've been checked in: once someone has played,
// their attendance, XP and badges stay (progress only goes up).
export async function removeTicket(form: FormData) {
  const { supabase } = await requireAdmin();
  const ticketId = text(form, "ticket_id", 64);
  const sessionId = text(form, "session_id", 64);
  const playerId = text(form, "player_id", 64);
  const path = `/admin/players?session=${sessionId}`;
  if (!ticketId || !sessionId || !playerId) back(path, "Missing ticket.");
  const { data: here } = await supabase.from("attendance").select("player_id").eq("session_id", sessionId).eq("player_id", playerId);
  if (rows(here).length) back(path, "They already played this session, so their ticket stays.");
  const { error } = await supabase.from("ticket").delete().eq("id", ticketId);
  revalidatePath("/admin/players");
  back(path, error ? "Couldn't remove the ticket." : "Ticket removed. Their pass stays, but they're off this session's list.");
}
